Repository AY2223S1-CS2103-F13-2/tp, pull requests merged in 2022-10, with the labels that each got.

#95 Update URL for HelpWindow
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: type.Bug, priority.High, severity.High

#87 Add UndoCommand by saving previous states
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/UndoCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/VersionedAddressBook.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/UndoCommandTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/UndoCommandParserTest.java
Labels: priority.Medium

#121 Improve DeleteCommand for multiple surveys
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
Labels: type.Enhancement, priority.Medium, severity.Medium

#124 Improve clone command
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/CloneCommand.java
  src/main/java/seedu/address/logic/parser/CloneCommandParser.java
  src/test/java/seedu/address/logic/commands/CloneCommandTest.java
  src/test/java/seedu/address/logic/commands/ClonePersonDescriptorTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/CloneCommandParserTest.java
  src/test/java/seedu/address/testutil/ClonePersonDescriptorBuilder.java
Labels: type.Enhancement

#143 Fix behaviour of mark and unmark command
  src/main/java/seedu/address/logic/commands/MarkCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkCommand.java
Labels: type.Bug, priority.High, severity.Medium

#206 Fix TOC
  docs/UserGuide.md
Labels: type.Bug, priority.High, severity.Medium

#209 Add more tests to `delete`
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
Labels: type.Enhancement, priority.Medium, severity.Medium
